apiVersion: v1
kind: Service
metadata:
  name: bookingbyuser
  labels:
    app: acmeair
spec:
  selector:
    app: acmeair
    tier: booking-byuser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

